### PR TITLE
Launcher icon settings shortcut

### PR DESCRIPTION
**Pull request by nodinosaur**
Found a need to be able to get to Settings directly from launcher, where a badly configured url was not allowing the system navigation to pop up & thus not able to press back & get to the Settings screen.
The shortcut is enabled by long pressing on the Wallpanel launcher icon.

### CODE REVIEW

**Comment by thanksmister** [comment]
Thanks the badly needed fix!!

**Comment by thanksmister** [comment]
It looks like you did not check-in the string resources used for the project.

**Comment by nodinosaur** [comment]
Hey Michael,

Do you have an idea of which ones?
I just reviews
https://github.com/thanksmister/wallpanel-android/pull/81/files again and
can't see what might be missing and have also downloaded the ZIP from
https://github.com/thanksmister/wallpanel-android (which as you'll know is
based off the master branch) as a completely fresh project and compiled it
into a clean emulator image and had no warnings and the launcher shortcut
seems to work as intended.


Thanks,

George

**Comment by thanksmister** [comment]
Looks like just my local build, but someone reported that on Android 9, the application continually opened to the settings when the application was dismissed.   I am investigating this issue to see if it was just a bad build (my missing strings locally) or if there is some issue with the launch on Android 9.  I will let you know what I find, in the meantime I rolled back the production release of the new feature until I finish investigating.

**Comment by nodinosaur** [comment]
I was about to suggest maybe giving the project a clean.
I am testing the build on Android 9 (emulator) here myself and seems to
work as expected.
See you at I/O?


This transmission is intended only for the party to whom it is addressed
and may contain privileged and confidential information.
If you are not the intended recipient, any use, dissemination, or copying
of this transmission is prohibited.

**Comment by nodinosaur** [comment]
Crap, I have just seen the error.

please remove: Line 44 in LauncherShortcuts

https://github.com/thanksmister/wallpanel-android/blob/master/WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/utils/LauncherShortcuts.kt#L44


email: george.medve@gmail.com
mobile: *+44 (0)7967 726 034*
twitter: @nodinosaur <http://twitter.com/nodinosaur>
instagram: @nodinosaur <https://www.instagram.com/nodinosaur/>
linkedin: profile <https://www.linkedin.com/in/george-m-86a1721/>

This transmission is intended only for the party to whom it is addressed
and may contain privileged and confidential information.
If you are not the intended recipient, any use, dissemination, or copying
of this transmission is prohibited.

**Comment by thanksmister** [comment]
I won't be at I/O since I am down here in Argentina, its too far to travel.   I will fix the issue, glad you spotted it.  It's not currently in production, so we are good for now.

**Comment by thanksmister** [comment]
I have updated the application and deploying the launcher code to production with the fix.  Thanks!

**Pull request merged**
